name: Python Package Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check for keyword in commit message
        id: keyword_check
        run: echo "contains_keyword=$(echo '${{ github.event.head_commit.message }}' | grep -qP '.(deploy|test)\b' && echo true || echo false)" >> $GITHUB_ENV

      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12.0"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install twine

      - name: Create & Push tag
        id: create_tag
        run: |
          TAG=$(echo '${{ github.event.head_commit.message }}' | grep -oP '.tag\[\K(.*?)(?=\])')
          if [ -n "$TAG" ]; then
            git tag $TAG
            git push origin $TAG
          else
            TAG="NULL"
            git tag $TAG
            git push origin $TAG
            echo "No tag found in commit message. Using default tag."
          fi
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build package
        run: python -m build

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.create_tag.outputs.TAG }}
        with:
          tag_name: ${{ env.TAG }}
          draft: false
          prerelease: false

      - name: Publish package to PyPI
        if: contains(github.event.head_commit.message, '.deploy')
        run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      - name: Publish package to TestPyPI
        if: contains(github.event.head_commit.message, '.test')
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
